# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd85b7529ef4626f019d9bea90df27732dcf8bb2a12ca9309e24507239ae4ae8bdbce8aba9da2630f880a3af7bae432c270739462e32e752594b715e851041bf

test:
  secret_key_base: cc6b40e83cf232172298bcb062ea3d8853f7a6630b955480b6d2d239847673db327846b946436679c056849ee2e0ba33da46b8b6a83b7f1f1a8704463b8f3c5a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
